### ISSUE TITLE
feat: add MacOS configs

### ISSUE THREAD

**Issue by realeinherjar** [realeinherjar/flakes#60]
We need to leave `brew`. It is a shitcoin in Ruby.

This is going to be a huge TODO list, but in much need.
Start from scratch:

- [ ] backup `main` to a `nix-os` branch
- [ ] copy `books` and `music`
- [ ] use the `both` template from [`nixos-flakes`](https://zero-to-flakes.com/nixos-flake/templates) : `nix flake init -t github:srid/nixos-flake`
- [ ] username: `einherjar`
- [ ] hostname: `macbook`
- [ ] follow `nixpkgs-unstable`
- [ ] OPTIONAL: [`yabai`](https://cmacr.ae/blog/yabai-module-in-nix-darwin-now-generally-available/)
- [ ] add all `brew` packages in https://github.com/realeinherjar/MacOS/blob/b2826c28121e5fc05805463c0b4793d86f3f9579/setup.sh#L17-L79 to packages
  - [ ] add [`delta`](https://github.com/dandavison/delta), also update the [`git` configs](https://nix-community.github.io/home-manager/options.html#opt-programs.git.delta.enable) and [getting started from `delta` configs](https://github.com/dandavison/delta?tab=readme-ov-file#get-started)
  - [ ] add `alacritty`
    - [ ] [`catppuccin` colorscheme](https://github.com/alacritty/alacritty-theme/blob/master/themes/catppuccin.yaml) (check if matches with `catppuccin_mocha`)
    - [ ] some options:
       ```yml
       env:
         TERM: xterm-256color
       shell:
         program: zsh
         args:
           - -l
           - -c
           - "source ~/.zshrc; tmux attach 2> /dev/null || tmux"
       window:
         decorations: buttonless
         opacity: 1.0
         window_decorations_theme: dark
         columns: 0
         lines: 0
         startup_mode: Windowed
       font:
         normal:
           family: "NotoSans Nerd Font"
         size: 12.09
       hints:
         enabled:
           - regex:
               "(ipfs:|ipns:magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|www)\
               [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
             command: open
             post_processing: true
             mouse:
               enabled: true
               mods: Command
             binding:
               key: U
               mods: Command|Shift
       live_config_reload: true
       ```
- [ ] add all `cask` packages in https://github.com/realeinherjar/MacOS/blob/b2826c28121e5fc05805463c0b4793d86f3f9579/setup.sh#L85-L106 to mac only
- [ ] use `direnv`, instructions [here](https://zero-to-flakes.com/direnv)
- [ ] README should follow [`srid/nixos-config`](https://github.com/srid/nixos-config) 
- [ ] Add all the hardening in https://github.com/realeinherjar/MacOS/blob/b2826c28121e5fc05805463c0b4793d86f3f9579/setup.sh#L141-L318 using the [`nix-darwin` configuration options](https://daiderd.com/nix-darwin/manual/index.html)
- [ ] Options from [`dustinlyons/nixos-config`](https://github.com/dustinlyons/nixos-config/blob/main/darwin/default.nix)
  - [ ] `darwin/default.nix`: `system`, `launchd`, `nix`, and `services`
- [ ] Migrate specific configs:
  - [ ] `modules/editors/helix.nix`
  - [ ] `modules/fonts/default.nix`
  - [ ] `modules/shell/tmux.nix`
  - [ ] `modules/programs/common/gpg/default.nix` (caveat: remove `pinentryFlavor`)
  - [ ] `modules/programs/common/ssh/default.nix`
  - [ ] `modules/programs/common/yt-dlp/default.nix` (maybe add this to `cli.nix`)
  - [ ] `modules/shell/git.nix`
  - [ ] `modules/shell/fish`:
    - [ ] update `fish_user_paths` in `modules/shell/fish/fish_variables.nix`
      - add a with `lib.mkIf pkgs.stdenv.isLinux` or `lib.mkIf pkgs.stdenv.isDarwin` to that concatenates either:
        - `SETUVAR fish_user_paths:/home/einherjar/\x2enpm\x2dglobal/bin\x1e/home/einherjar/\x2ecargo/bin`
        - `SETUVAR fish_user_paths:/Users/einherjar/\x2enpm\x2dglobal/bin\x1e/Users/einherjar/einherjar/\x2ecargo/bin`
    - [ ] Remove `n.nix`, `owf.nix`, `xdg-get.nix`, and `xdg-set.nix`
    - [ ] Remove the `loginShellInit` in `modules/shell/fish/fish.nix`
  - [ ] `modules/programs/common/search/default.nix` (maybe add this to `cli.nix`)
    - [ ] `fzf`
    - [ ] `bat`
    - [ ] `zoxide`
    - [ ] `yazi`
    - [ ] `eza`
    - [ ] `broot`
  - [ ] `btop` in `modules/programs/common/resource_monitor/default.nix`
- [ ] catppuccin everything:
  - [ ] `btop`: `modules/theme/catppuccin-dark/common/btop`
  - [ ] `fish`: `modules/theme/catppuccin-dark/common/fish/default.nix`
  - [ ] `bat`: <https://github.com/catppuccin/bat>
  - [ ] `btop`: <https://github.com/catppuccin/btop>
  - [ ] `fish`: <https://github.com/catppuccin/fish>
  - [ ] `fzf`: <https://github.com/catppuccin/fzf>
  - [ ] `tmux`: <https://github.com/catppuccin/tmux>
  - [ ] `lazygit`: <https://github.com/catppuccin/lazygit>
  - [ ] `alacritty`: <https://github.com/catppuccin/alacritty>
  - [ ] `cmus`: <https://github.com/Sekki21956/cmus>
